<a href="https://colab.research.google.com/github/JCF-the-creator/GoogleColabGeneration/blob/main/Aula6_Rock_%26_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
#- Desenvolver pipeline no Google Colab usando Pandas para leitura e validação dos 3 arquivos. x

#- Executar a concatenação vertical garantindo alinhamento de colunas. x

#- Tratamento de dados: Criar coluna Faturamento_Total e converter datas.

#- Exportar base consolidada final: trimestre_completo.csv.

import pandas as pd

In [66]:
df_jan = pd.read_csv("/content/vendas_janeiro.csv")
display(df_jan.head())

         Data                Produto  Preço  Qtd            Loja
0  2024-01-14  Microfone Condensador    654    9  Rio de Janeiro
1   2024-01-1         Baixo 4 Cordas   1169    1  Rio de Janeiro
2   2024-01-4       Bateria Acústica   2964    1        Curitiba
3  2024-01-27           Violão Nylon   4352    6  Rio de Janeiro
4  2024-01-12         Baixo 4 Cordas    709   10       São Paulo

In [67]:
df_fev = pd.read_csv("/content/vendas_fevereiro.csv")
display(df_fev.head())

         Data                Produto  Preço  Qtd            Loja
0  2024-02-12        Teclado Digital   3757    8  Belo Horizonte
1  2024-02-25         Baixo 4 Cordas   2636    5  Rio de Janeiro
2  2024-02-22        Teclado Digital   3403    4       São Paulo
3  2024-02-25  Microfone Condensador   4280    8       São Paulo
4   2024-02-5         Baixo 4 Cordas   1344    7  Rio de Janeiro

In [68]:
df_mar = pd.read_csv("/content/vendas_marco.csv")
display(df_mar.head())

         Data                Produto  Preço  Qtd            Loja
0   2024-03-6  Microfone Condensador   3462    5       São Paulo
1  2024-03-12        Teclado Digital   3146    4        Curitiba
2  2024-03-20           Violão Nylon   3502    4        Curitiba
3  2024-03-14       Bateria Acústica   2309   10  Rio de Janeiro
4  2024-03-21        Teclado Digital   3020    9       São Paulo

In [69]:
df_dados_juntos = pd.concat([df_jan, df_fev, df_mar], ignore_index=True)
display(df_dados_juntos)

           Data                Produto  Preço  Qtd            Loja
0    2024-01-14  Microfone Condensador    654    9  Rio de Janeiro
1     2024-01-1         Baixo 4 Cordas   1169    1  Rio de Janeiro
2     2024-01-4       Bateria Acústica   2964    1        Curitiba
3    2024-01-27           Violão Nylon   4352    6  Rio de Janeiro
4    2024-01-12         Baixo 4 Cordas    709   10       São Paulo
..          ...                    ...    ...  ...             ...
160  2024-03-21        Teclado Digital   2654    4  Rio de Janeiro
161  2024-03-14       Amplificador 50W   1170    8        Curitiba
162  2024-03-24           Violão Nylon   3556   10  Belo Horizonte
163  2024-03-28       Bateria Acústica   2742    1       São Paulo
164  2024-03-24  Microfone Condensador   2970    8        Curitiba

[165 rows x 5 columns]

In [70]:
df_dados_juntos['Faturamento'] = df_dados_juntos['Preço'] * df_dados_juntos["Qtd"]
df_dados_juntos.to_csv("trimestre_completo.csv", index=False)
display(df_dados_juntos)

,Data,Produto,Preço,Qtd,Loja,Faturamento
0,2024-01-14,Microfone Condensador,654,9,Rio de Janeiro,5886
1,2024-01-1,Baixo 4 Cordas,1169,1,Rio de Janeiro,1169
2,2024-01-4,Bateria Acústica,2964,1,Curitiba,2964
3,2024-01-27,Violão Nylon,4352,6,Rio de Janeiro,26112
4,2024-01-12,Baixo 4 Cordas,709,10,São Paulo,7090
...,...,...,...,...,...,...
160,2024-03-21,Teclado Digital,2654,4,Rio de Janeiro,10616
161,2024-03-14,Amplificador 50W,1170,8,Curitiba,9360
162,2024-03-24,Violão Nylon,3556,10,Belo Horizonte,35560
163,2024-03-28,Bateria Acústica,2742,1,São Paulo,2742
164,2024-03-24,Microfone Condensador,2970,8,Curitiba,23760